Add Node-RED service
home-assistant/hassbian-scripts pull request #167
Opened 2018-05-21 13:43 UTC by cxlwill

## Description:

**Related issue (if applicable):** Fixes #33 (2)

## Checklist (Required):
  - [x] The code change is tested and works locally.
  - [x] The code is compliant with [Contributing guidelines](https://github.com/home-assistant/hassbian-scripts/blob/master/.github/CONTRIBUTING.md)

### If pertinent:
  - [x] Script has validation check of the job.
  - [x] Created/Updated documentation at `/docs`

2018-06-04 17:11 UTC, ludeeus commented
@cxlwill I tried your script but it gave me this error:
https://hastebin.com/udiyizuhaf.erl

Same result for second run:
https://hastebin.com/ukenaxetow.sql

2018-07-04 19:27 UTC, Landrash requested changes
Some minor tweaks would be preferable but looks good in general.

2018-07-04 19:27 UTC, Landrash commented on package/opt/hassbian/suites/nodered.sh
> +sudo wget https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/nodered.service -O /lib/systemd/system/nodered.service
These files would preferably be included in this package to avoid downloads from a repo that may change.

2018-07-04 19:27 UTC, Landrash commented on package/opt/hassbian/suites/nodered.sh
> +npm install node-red-contrib-home-assistant
There's a prebuilt package available in apt

```
pi@hassbian:~ $ apt search nodered
Sorting... Done
Full Text Search... Done
nodered/stable 0.18.7-1 armhf
  Node-RED flow editor for the Internet of Things
```

Is there any benefit for installing it like this?

2018-07-04 19:27 UTC, Landrash commented on package/opt/hassbian/suites/nodered.sh
> +sleep 2 #Node-red needs seconds to launch or Installation Check would fail
Bump this to 5 second in case this is installed on a busy system.
It won't mater to most since the install is most likely much longer than this.

2019-04-02 10:37 UTC, Landrash commented
Closing since commit had been stale for 9 months.

2019-04-02 10:37 UTC, closed without merging