Add install script for fail2ban
home-assistant/hassbian-scripts pull request #211
Opened 2018-10-28 20:59 UTC by Landrash

## Description:
Adds a installation script of the [fail2ban](https://github.com/fail2ban/fail2ban) service.

## Checklist (Required):
  - [x] The code change is tested and works locally.
  - [x] The code is compliant with [Contributing guidelines](https://github.com/home-assistant/hassbian-scripts/blob/master/.github/CONTRIBUTING.md)

### If pertinent:
  - [x] Script has validation check of the job.
  - [x] Created/Updated documentation at `/docs`

2018-10-29 07:39 UTC, ludeeus reviewed
Added some minor comments, other than those it looks good :)

2018-10-29 07:39 UTC, ludeeus commented on package/opt/hassbian/suites/fail2ban.sh
> +bantime = 30 # during testing it is useful to have a short ban interval, comment out this line later
Does Fail2Ban allow duplicates in the configuration?
Or should one of these be commented out by default?

2018-10-29 07:39 UTC, ludeeus commented on docs/fail2ban.md
> +# Monitor
```suggestion
# Fail2Ban
```
Added suggestion for a title change.

2018-10-29 18:06 UTC, ludeeus requested changes
Two minor changes :)

2018-10-29 18:06 UTC, ludeeus commented on package/opt/hassbian/suites/fail2ban.sh
> +bantime = 30 # during testing it is useful to have a short ban interval, comment out this line later
```suggestion
#bantime = 30 # during testing it is useful to have a short ban interval, comment out this line later
```
Tested the script now, the service fails if both are present.

2018-10-29 18:06 UTC, ludeeus commented on package/opt/hassbian/suites/fail2ban.sh
> +validation=$(which -x fail2ban-client)
This results in `Illegal option -x`

```suggestion
validation=$(which fail2ban-client)
```

2018-10-31 18:43 UTC, Landrash commented
Changes applied ☺️

2018-10-31 19:36 UTC, ludeeus approved these changes

2018-10-31 19:36 UTC, merged