Preparations for Python 3.5 D-Day.
home-assistant/hassbian-scripts pull request #255
Opened 2019-04-15 09:41 UTC by ludeeus

## Description:

**Testing not yet completed** 
_Marked as "draft" until testing are done_

**Related issue (if applicable):** Fixes #<hassbian-scripts issue number goes here>

## Checklist (Required):
  - [ ] The code change is tested and works locally.
  - [ ] The code is compliant with [Contributing guidelines](https://github.com/home-assistant/hassbian-scripts/blob/master/.github/CONTRIBUTING.md)

### If pertinent:
  - [x] Script has validation check of the job.
  - [x] Created/Updated documentation at `/docs`

2019-04-15 10:43 UTC, ludeeus commented on package/opt/hassbian/suites/python.sh
> +  currentversion$("python${PYTHONVERSION:0:3} -V")
There is **nothing** more left to quote...

2019-04-21 21:02 UTC, Landrash approved these changes

2019-04-21 21:05 UTC, Landrash requested changes
systeminfo is missing form "tab completion"

2019-04-21 21:06 UTC, Landrash requested changes
Error on Stretch

> Checking current version...
3.5.3/opt/hassbian/suites/python.sh: line 29: python3.7: command not found
Upgrading to Python 3.7.3

2019-04-22 10:11 UTC, Landrash approved these changes
LGTM. Tested on Stretch and Buster

2019-04-22 10:11 UTC, merged