Docs: Corrected links and anchors
home-assistant/hassbian-scripts pull request #299
Opened 2019-05-25 11:03 UTC by jobr97

# Description

All relative links in the documentation were missing `'/hassbian-scripts'` and therefore resulted in 404. This PR fixes that along with some anchors (mainly in `/cli/helpers`).

[guidelines]: https://github.com/home-assistant/hassbian-scripts/blob/master/.github/CONTRIBUTING.md

2019-05-25 11:47 UTC, homeassistant commented
Hi @jobr97, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassbian-scripts#299).

Once you do that we will be able to review and accept this pull request.

Thanks!

2019-05-28 10:40 UTC, Landrash requested changes
Looks good with one minor tweak necessary

2019-05-28 10:40 UTC, Landrash commented on docs/contribute/index.md
> +<<<<<<< HEAD
Merge diff left in commit

2019-05-28 13:13 UTC, jobr97 commented
Should be good now @Landrash 😄

2019-05-28 14:01 UTC, ludeeus requested changes

2019-05-28 14:01 UTC, ludeeus commented on docs/cli/index.md
> +>>>>>>> f989be3d831fb22831166612aca6cf108fd2a1cd
One more :)

2019-05-28 14:15 UTC, jobr97 commented on docs/cli/index.md
> +>>>>>>> f989be3d831fb22831166612aca6cf108fd2a1cd
Damn... 
This should be the last one 😅

2019-05-28 14:46 UTC, Landrash approved these changes

2019-05-28 14:47 UTC, Landrash commented
@Luddeus feel free to merge when your block is gone 👍

2019-05-28 19:02 UTC, ludeeus approved these changes

2019-05-28 19:02 UTC, merged