Update upgrade_home-assistant.sh
home-assistant/hassbian-scripts pull request #71
Opened 2017-11-04 21:52 UTC by riemers

Added a so that it skips upgrading if the version is already installed. If you want to be on the edge you can now crontab the upgrade or similar. Perhaps there is a better way, but this one seemed ok. Don't really need that json function but it might be handy for other stuff too.

2017-11-04 21:52 UTC, homeassistant commented
Hi @riemers, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassbian-scripts#71).

Once you do that we will be able to review and accept this pull request.

Thanks!

2017-11-04 21:59 UTC, Landrash requested changes
Looks great with a minor adjustment requested for usability.

2017-11-04 21:59 UTC, Landrash commented on package/opt/hassbian/suites/upgrade_home-assistant.sh
> +        echo "Stopping upgrade"
A bit more descriptive error message and this is good to merge

2017-11-04 22:20 UTC, riemers commented on package/opt/hassbian/suites/upgrade_home-assistant.sh
> +sudo -u homeassistant -H /bin/bash << EOF | grep Version|awk '{print $2'}|while read version; do if [[ ${versiongit} == ${version} ]]; then echo "You already have the latest version: $version";exit 1
This line has the more descriptive error message, but since its in the pipe of the EOF i did it here otherwise you loose the string value.

2018-01-27 12:21 UTC, Landrash approved these changes
Looks good and tagged for 0.7.

2018-01-27 12:23 UTC, merged