Chromium kiosk mode for attached touchscreen
home-assistant/hassbian-scripts pull request #97
Opened 2018-02-08 15:21 UTC by ardeus-ua

2018-02-08 15:21 UTC, homeassistant commented
Hi @ardeus-ua, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassbian-scripts#97).

Once you do that we will be able to review and accept this pull request.

Thanks!

2018-02-09 06:09 UTC, Landrash commented
@ardeus-ua Can you merge your 3 Pr's into one? It makes it a tad hard to test as is :smile:

2018-02-09 10:26 UTC, ardeus-ua commented
Sorry, this was my first pull. Will check how to do it

2018-02-09 10:32 UTC, ludeeus commented
@ardeus-ua you can push the other scripts to your branch with name "path-1"

2018-02-21 20:54 UTC, ardeus-ua commented
updated patch-1 branch. Please review

2018-02-24 19:04 UTC, ludeeus requested changes
I have now tested this on an fresh install of Hassbian, and there are some issues that need to be corrected, I have added some comments to the files.

Once I moved the script, it did try to execute but gave the this error: https://hastebin.com/dibehoxide

You should also create documentation for this.
See <https://github.com/home-assistant/hassbian-scripts/tree/dev/docs> for inspiration.

2018-02-24 19:04 UTC, ludeeus commented on package/opt/hassbian/suites/kiosk.sh
> +function hue-show-short-info {
Wrong function should be kiosk-show-short-info

2018-02-24 19:04 UTC, ludeeus commented on package/opt/hassbian/suites/kiosk.sh
> +function hue-show-long-info {
Wrong function should be kiosk-show-long-info

2018-02-24 19:04 UTC, ludeeus commented on package/opt/hassbian/suites/kiosk.sh
> +function hue-show-copyright-info {
Wrong function should be kiosk-show-copyright-info

2018-02-24 19:04 UTC, ludeeus commented on package/opt/hassbian/suites/kiosk.sh
> +apt-get --no-install-recommends install xserver-xorg xserver-xorg-video-fbdev xinit pciutils xinput xfonts-100dpi xfonts-75dpi xfonts-scalable
Missing `-y` flag, script execution hangs.

2018-02-24 19:04 UTC, ludeeus commented on package/opt/hassbian/suites/kiosk.sh
> +apt-get -y --force-yes install screen checkinstall xterm xdotool x11-xserver-utils unclutter chromium-browser x11vnc expect
--force-yes is deprecated, use one of the options starting with --allow instead.

2018-02-24 19:04 UTC, ludeeus commented on package/opt/hassbian/suites/kiosk.sh
> +sudo -u pi /home/pi/setX11vncPass raspberry
You are copying this to /home/pi/scripts/setX11vncPass
But are running from /home/pi/setX11vncPass
Resulting in "sudo: /home/pi/setX11vncPass: command not found"
Why not have it in the right dir by default?

2018-02-24 19:04 UTC, ludeeus commented on package/opt/hassbian/suites/kiosk.sh
> +  sudo -u pi /home/pi/scripts/setX11vncPass raspberry
The passord should be user defined for this.
With fallback to default if user don't supply one, see mosquitto or homebridge scripts for how you can manage this.

2018-02-24 19:04 UTC, ludeeus commented on package/opt/hassbian/suites/kiosk.sh
> +echo "Installation done."
Can you implement an validation check for this script?
See #121 for examples

2018-02-24 19:04 UTC, ludeeus commented on package/opt/hassbian/suites/kiosk.sh
> +echo "sudo -u pi startx /home/pi/scripts/kiosk &" >> /etc/rc.local
This is added after the `exit` in /etc/rc.local and will never be executed.

2018-02-24 19:04 UTC, ludeeus commented on package/opt/hassbian/suites/kiosk.sh
> +echo
Since this wont take affect until you reboot or logout/login.
This should be mentioned.

2018-04-02 15:37 UTC, ludeeus commented
@ardeus-ua are you still working on this?

2018-04-02 16:56 UTC, ardeus-ua commented
@ludeeus trying to make it work but no results so far.

2018-06-19 08:34 UTC, ludeeus commented
@ardeus-ua  any update on this?

2018-10-01 16:24 UTC, ludeeus commented
Closing down this now, it can be revisited at a later stage.

2018-10-01 16:24 UTC, closed without merging